### ISSUE TITLE
Release not compatible with CentOS stemcell

### ISSUE THREAD

**Issue by osaluden** [orange-cloudfoundry/mongodb-boshrelease#28]
Compiled mongod binary (/var/vcap/packages/mongodb/bin/mongod) not linked to required library/

On CentOS 7.4 stemcell:

```shell
# for package_lib_dir in $(ls -d /var/vcap/packages/*/lib /var/vcap/packages/*/lib64)
> do
> export LD_LIBRARY_PATH=${package_lib_dir}:$LD_LIBRARY_PATH
> done

# ldd /var/vcap/packages/mongodb/bin/mongod
/var/vcap/packages/mongodb/bin/mongod: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /var/vcap/packages/mongodb/lib64/libstdc++.so.6)
        linux-vdso.so.1 =>  (0x00007ffcc3b6e000)
        libsnappy.so.1.1.5 => /var/vcap/packages/mongodb/lib/libsnappy.so.1.1.5 (0x00007f5246fa1000)
        liblz4.so.1 => /var/vcap/packages/mongodb/lib/liblz4.so.1 (0x00007f5246d86000)
        libzstd.so.1 => /var/vcap/packages/mongodb/lib/libzstd.so.1 (0x00007f5246b04000)
        libz.so.1 => /var/vcap/packages/mongodb/lib/libz.so.1 (0x00007f52468e9000)
        libssl.so.1.0.0 => not found
        libcrypto.so.1.0.0 => not found
        librt.so.1 => /lib64/librt.so.1 (0x00007f52466d7000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f52464d2000)
        libstdc++.so.6 => /var/vcap/packages/mongodb/lib64/libstdc++.so.6 (0x00007f5246158000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f5245e56000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f5245c3f000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f5245a23000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f5245660000)
        /lib64/ld-linux-x86-64.so.2 (0x000055c1f6aa6000)
```
**libssl.so.1.0.0** and  **libcrypto.so.1.0.0** are missing.
On CentOS 7.4, libssl and libcrypto are located in /usr/lib64 and version 1.0.2k

Example on a working deployment (Ubuntu trusty stemcell):

```shell
# for package_lib_dir in $(ls -d /var/vcap/packages/*/lib /var/vcap/packages/*/lib64)
> do
> export LD_LIBRARY_PATH=${package_lib_dir}:$LD_LIBRARY_PATH
> done

# ldd /var/vcap/packages/mongodb/bin/mongod
        linux-vdso.so.1 =>  (0x00007ffc8cd0e000)
        libsnappy.so.1.1.5 => /var/vcap/packages/mongodb/lib/libsnappy.so.1.1.5 (0x00007f7e80c5a000)
        liblz4.so.1 => /var/vcap/packages/mongodb/lib/liblz4.so.1 (0x00007f7e80a3f000)
        libzstd.so.1 => /var/vcap/packages/mongodb/lib/libzstd.so.1 (0x00007f7e807bd000)
        libz.so.1 => /var/vcap/packages/mongodb/lib/libz.so.1 (0x00007f7e805a2000)
        libssl.so.1.0.0 => /lib/x86_64-linux-gnu/libssl.so.1.0.0 (0x00007f7e8033d000)
        libcrypto.so.1.0.0 => /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007f7e7ff60000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f7e7fd58000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f7e7fb54000)
        libstdc++.so.6 => /var/vcap/packages/mongodb/lib64/libstdc++.so.6 (0x00007f7e7f7d9000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f7e7f4d3000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f7e7f2bd000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f7e7f09e000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f7e7ecd5000)
        /lib64/ld-linux-x86-64.so.2 (0x000055d520704000)
```

**libssl.so.1.0.0** and  **libcrypto.so.1.0.0** are located in /lib/x86_64-linux-gnu on Ubuntu Trustry.

**Comment by bgandon** [comment]
@osaluden : can you find any `libssl*` or `libcrypto*` on your CentOS stemcell, just with simple find commands like `find / -name 'libssl*'` and `find / -name 'libcrypto*'`?

@jraverdy-orange : after we fix this, maybe we should add a CentOS-specific sub-pipeline in our Concourse, don't you think? (Indeed, we though we were OK with CentOS, whereas it looks like it's not the case because we didn't actually test it.)

**Comment by jraverdy-orange** [comment]
@bgandon : ssl libs are definitely not included in centos stemcell, i had to add them to the mongo archive. The correction and the centos dedicated pipeline have already been done. Just doin some tests before providing a new final release

**Comment by osaluden** [comment]
Here is the libssl* and libcrypto* search result on the CentOS stemcell:

```shell
# find / -name 'libssl*' && find / -name 'libcrypto*'
/usr/lib64/libssl3.so
/usr/lib64/pkgconfig/libssl.pc
/usr/lib64/libssl.so
/usr/lib64/libssl.so.10
/usr/lib64/libssl.so.1.0.2k
/usr/lib64/libcrypto.so
/usr/lib64/libcrypto.so.1.0.2k
/usr/lib64/libcrypto.so.10
/usr/lib64/pkgconfig/libcrypto.pc
```

**Comment by jraverdy-orange** [comment]
@osaluden : i didnt take a look here :$  this path is not included in the ld_library_path... 
I'll provide my own ssl libs with the package to make it more portable. I also have to include libc.so.6

**Comment by bgandon** [comment]
I think the problem is mainly a name mismatch between `libssl.so.1.0.0` and `libcrypto.so.1.0.0` on Ubuntu, and `libssl.so.10` and `libcrypto.so.10` on CentOS.

The problem with shipping the SSL libraries is that this would lead us to implement a strict monitoring on the SSL vulnerabilities and thus a strict patching policy. Ultimately this would lead us to ship kind of “spurious” mongodb release versions that would just ship some patched SSL library.

We really should let the responsibility of providing a patched SSL library to the Stemcell provider. Thus, I think the best thing to do here, is to fix the naming issue with SSL libraries. I'll try to find some clue about that on the net.

I'm really not in favor that we ship the `libm.so.6` with the static binaries either, for similar reasons. Plus, it's a heavy library.

**Comment by jraverdy-orange** [comment]
Centos stemcell is not supported by the release anymore
